fail-on-severity: high
license-check: true
vulnerability-check: true

allow-licenses:
  - 0BSD
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - BlueOak-1.0.0
  - CC0-1.0
  - ISC
  - MIT
  - Python-2.0
  - Zlib

allow-dependencies-licenses:
  - pkg:npm/%40azu/style-format
  - pkg:npm/%40vscode/vsce-sign
  - pkg:npm/%40vscode/vsce-sign-alpine-arm64
  - pkg:npm/%40vscode/vsce-sign-alpine-x64
  - pkg:npm/%40vscode/vsce-sign-darwin-arm64
  - pkg:npm/%40vscode/vsce-sign-darwin-x64
  - pkg:npm/%40vscode/vsce-sign-linux-arm
  - pkg:npm/%40vscode/vsce-sign-linux-arm64
  - pkg:npm/%40vscode/vsce-sign-linux-x64
  - pkg:npm/%40vscode/vsce-sign-win32-arm64
  - pkg:npm/%40vscode/vsce-sign-win32-x64
  - pkg:npm/binaryextensions
  - pkg:npm/editions
  - pkg:npm/istextorbinary
  - pkg:npm/textextensions
  - pkg:npm/version-range
  - pkg:npm/caniuse-lite
  - pkg:npm/lightningcss
  - pkg:npm/lightningcss-android-arm64
  - pkg:npm/lightningcss-darwin-arm64
  - pkg:npm/lightningcss-darwin-x64
  - pkg:npm/lightningcss-freebsd-x64
  - pkg:npm/lightningcss-linux-arm-gnueabihf
  - pkg:npm/lightningcss-linux-arm64-gnu
  - pkg:npm/lightningcss-linux-arm64-musl
  - pkg:npm/lightningcss-linux-x64-gnu
  - pkg:npm/lightningcss-linux-x64-musl
  - pkg:npm/lightningcss-win32-arm64-msvc
  - pkg:npm/lightningcss-win32-x64-msvc
  - pkg:npm/ovsx
  - pkg:npm/spdx-exceptions
